# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "1e2ea194936f842886ec83c956519710"
name = "my-node-app"
handle = "my-node-app-316"
application_url = "https://compare-bookstore-surrounding-belkin.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "teststo1222.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://compare-bookstore-surrounding-belkin.trycloudflare.com/auth/callback",
  "https://compare-bookstore-surrounding-belkin.trycloudflare.com/auth/shopify/callback",
  "https://compare-bookstore-surrounding-belkin.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
